### ISSUE TITLE
[Question, Feature] GroupHeader

### ISSUE THREAD

**Issue by DevEddy** [KishanDonga/Xamarin-GridView#1]
Hey,

have you ever considered to implement GroupHeader? 
Have you tips of how to implement it in your GridView?

Thanks,
Eddy

**Comment by kishandonga** [comment]
Sorry for too late replay but I didn't try to implement GroupHeader it is a simple grid view or we can say data grid as shown in the example. But if you want to enhance and need any help to code understanding feel free to connect with me.
